export const themeData = JSON.parse("{\"blog\":{},\"encrypt\":{},\"pure\":true,\"darkmode\":\"toggle\",\"themeColor\":false,\"fullscreen\":false,\"locales\":{\"/\":{\"blog\":{},\"repoDisplay\":true,\"navbarIcon\":true,\"navbarAutoHide\":\"mobile\",\"hideSiteNameonMobile\":true,\"sidebar\":{\"/question/\":\"structure\",\"/plugin/advanced-access-manager/\":\"structure\",\"/plugin/protected-media-files/\":\"structure\",\"/plugin/premium-complete-package/\":\"structure\",\"/reference/access-policy/\":\"structure\",\"/reference/cli/\":\"structure\",\"/reference/restful-api/\":\"structure\",\"/reference/dev-api/\":\"structure\"},\"sidebarIcon\":true,\"headerDepth\":2,\"lang\":\"en-US\",\"navbarLocales\":{\"langName\":\"English\",\"selectLangAriaLabel\":\"Select language\"},\"metaLocales\":{\"author\":\"Author\",\"date\":\"Writing Date\",\"origin\":\"Original\",\"views\":\"Page views\",\"category\":\"Category\",\"tag\":\"Tag\",\"readingTime\":\"Reading Time\",\"words\":\"Words\",\"toc\":\"On This Page\",\"prev\":\"Prev\",\"next\":\"Next\",\"lastUpdated\":\"Last update\",\"contributors\":\"Contributors\",\"editLink\":\"Edit this page on GitHub\"},\"outlookLocales\":{\"themeColor\":\"Theme Color\",\"darkmode\":\"Theme Mode\",\"fullscreen\":\"Full Screen\"},\"encryptLocales\":{\"iconLabel\":\"Page Encrypted\",\"placeholder\":\"Enter password\",\"remember\":\"Remember password\",\"errorHint\":\"Please enter the correct password!\"},\"routeLocales\":{\"notFoundMsg\":[\"There’s nothing here.\",\"How did we get here?\",\"That’s a Four-Oh-Four.\",\"Looks like we've got some broken links.\"],\"back\":\"Go back\",\"home\":\"Take me home\",\"openInNewWindow\":\"Open in new window\"},\"author\":{\"name\":\"Vasyl Martyniuk\",\"url\":\"https://vasyltech.com\"},\"logo\":\"/assets/logo/aam-light.svg\",\"logoDark\":\"/assets/logo/aam-dark.svg\",\"repo\":\"aamplugin/docs\",\"editLinkPattern\":\":repo/:branch/src/:path\",\"pageInfo\":[\"Author\",\"Original\",\"Date\",\"Category\",\"Tag\",\"ReadingTime\"],\"navbar\":[{\"text\":\"Home\",\"link\":\"/\"},{\"text\":\"Resources\",\"children\":[{\"text\":\"Some Stuff To Read\",\"children\":[{\"text\":\"Get Started\",\"link\":\"/get-started\"},{\"text\":\"How to..?\",\"link\":\"/question/\"},{\"text\":\"Free E-Books\",\"link\":\"/e-books\"}]},{\"text\":\"Plugins\",\"children\":[{\"text\":\"Advanced Access Manager\",\"link\":\"/plugin/advanced-access-manager/\"},{\"text\":\"Protected Media Files\",\"link\":\"/plugin/protected-media-files/\"},{\"text\":\"Premium Complete Package\",\"link\":\"/plugin/premium-complete-package/\"}]},{\"text\":\"Advanced Topics\",\"children\":[{\"text\":\"JSON Access Policy\",\"link\":\"/reference/access-policy/\"},{\"text\":\"CLI\",\"link\":\"/reference/cli/\"},{\"text\":\"RESTful API\",\"link\":\"/reference/restful-api/\"},{\"text\":\"Developer API\",\"link\":\"/reference/dev-api/\"}]}]}],\"footer\":\"Default footer\",\"displayFooter\":true}}}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateThemeData) {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ themeData }) => {
    __VUE_HMR_RUNTIME__.updateThemeData(themeData)
  })
}
